[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | env/*
    | migrations/*
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
[tool.isort]
profile = "black"
skip_glob = '**/migrations/**'
line_length = 120
length_sort = true
