name: Code Style CI

on:
  pull_request:

jobs:
  project-lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -U pip setuptools
        pip install -r requirements.style.txt

    - name: Style check
      run: make lint
